# Este fluxo de trabalho criará um projeto Java com Maven e armazenará em cache/restaurará todas as dependências para melhorar o tempo de execução do fluxo de trabalho

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
         
    #  Neste job é executado os Testes de Componentes com K6  
    - name: Configurar ambiente Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14'
    - name: Instalar dependências do projeto
      run: npm ci

    - name: Executar testes de componentes
      run: npx k6 run --quiet ./tests/component-tests.js

   
     
