# Este fluxo de trabalho criará um projeto Java com Maven e armazenará em cache/restaurará todas as dependências para melhorar o tempo de execução do fluxo de trabalho

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      
      
    # Neste job é executado os Testes Unitários  
    - name: Compilar e executar testes
      run: mvn test --batch-mode
      
    #  Neste job é executado os Testes de Componentes com K6  
    - name: Configurar ambiente Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14'
    - name: Instalar dependências do projeto
      run: npm ci

    - name: Executar testes de componentes
      run: npx k6 run --quiet ./tests/component-tests.js

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
